language: node_js
os:
  - linux
  - osx
node_js:
  - "8"
  - "6"
before_install:
  - npm remove -g esy@next
  - npm install -g esy@next
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
